In [30]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
from sklearn.svm import LinearSVC,SVC,LinearSVR,SVR
from sklearn.preprocessing import StandardScaler,PolynomialFeatures
from sklearn import datasets
from sklearn.pipeline import Pipeline

# **LINEAR** **SVM**

## **Soft** **Margin** **Classification**

In [2]:
#to classify class-2 by petal length and width
irisd=datasets.load_iris()
iris=pd.DataFrame(irisd['data'])

X=iris.loc[:,[2,3]]
y=pd.DataFrame((irisd['target']==2).astype(np.int))

In [13]:
svm_clf=Pipeline([
                  ('std_scaler',StandardScaler()),
                  ('linear_svc',LinearSVC(C=1,loss='hinge',))
])

svm_clf.fit(X,y)

/usr/local/lib/python3.7/dist-packages/sklearn/utils/validation.py:760: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


Pipeline(memory=None,
         steps=[('std_scaler',
                 StandardScaler(copy=True, with_mean=True, with_std=True)),
                ('linear_svc',
                 LinearSVC(C=1, class_weight=None, dual=True,
                           fit_intercept=True, intercept_scaling=1,
                           loss='hinge', max_iter=1000, multi_class='ovr',
                           penalty='l2', random_state=None, tol=0.0001,
                           verbose=0))],
         verbose=False)

In [14]:
svm_clf.predict([[5.5,1.7]])

array([1])

# **NON** **-** **LINEAR** **SVM**

In [18]:
Xdata,ydata=datasets.make_moons(n_samples=100,noise=0.15)
X=pd.DataFrame(Xdata)
y=pd.DataFrame(ydata)

In [19]:
polynomial_svm_clf=Pipeline([
                             ('poly_features',PolynomialFeatures(degree=3)),
                             ('std_scaler',StandardScaler()),
                             ('poly_svm_clf',LinearSVC(C=10,loss='hinge'))
])

polynomial_svm_clf.fit(X,y)

/usr/local/lib/python3.7/dist-packages/sklearn/utils/validation.py:760: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


Pipeline(memory=None,
         steps=[('poly_features',
                 PolynomialFeatures(degree=3, include_bias=True,
                                    interaction_only=False, order='C')),
                ('std_scaler',
                 StandardScaler(copy=True, with_mean=True, with_std=True)),
                ('poly_svm_clf',
                 LinearSVC(C=10, class_weight=None, dual=True,
                           fit_intercept=True, intercept_scaling=1,
                           loss='hinge', max_iter=1000, multi_class='ovr',
                           penalty='l2', random_state=None, tol=0.0001,
                           verbose=0))],
         verbose=False)

In [20]:
print(X.head())
print(y.head())

          0         1
0  2.003347  0.480698
1  0.620850  0.547122
2  0.083267 -0.047103
3  1.584609 -0.030502
4 -0.202626  0.112464
   0
0  1
1  0
2  1
3  1
4  1


In [22]:
polynomial_svm_clf.predict([[2.003347,0.480698]])

array([1])

## **1.** **Polynomial** **Kernel**

In [26]:
poly_kernel_svm_clf=Pipeline([
                          ('std_scaler',StandardScaler()),
                          ('poly_kernel',SVC(kernel='poly',degree=3,coef0=1,C=5))

])

poly_kernel_svm_clf.fit(X,y)

/usr/local/lib/python3.7/dist-packages/sklearn/utils/validation.py:760: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


Pipeline(memory=None,
         steps=[('std_scaler',
                 StandardScaler(copy=True, with_mean=True, with_std=True)),
                ('poly_kernel',
                 SVC(C=5, break_ties=False, cache_size=200, class_weight=None,
                     coef0=1, decision_function_shape='ovr', degree=3,
                     gamma='scale', kernel='poly', max_iter=-1,
                     probability=False, random_state=None, shrinking=True,
                     tol=0.001, verbose=False))],
         verbose=False)

In [27]:
poly_kernel_svm.predict([[2.003347,0.480698]])

array([1])

## **2.** **Gaussian** **RBF** **Kernel**

In [28]:
rbf_kernel_svm_clf=Pipeline([
                          ('std_scaler',StandardScaler()),
                          ('poly_kernel',SVC(kernel='rbf',gamma=5,C=0.001))

])

rbf_kernel_svm_clf.fit(X,y)

/usr/local/lib/python3.7/dist-packages/sklearn/utils/validation.py:760: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


Pipeline(memory=None,
         steps=[('std_scaler',
                 StandardScaler(copy=True, with_mean=True, with_std=True)),
                ('poly_kernel',
                 SVC(C=0.001, break_ties=False, cache_size=200,
                     class_weight=None, coef0=0.0,
                     decision_function_shape='ovr', degree=3, gamma=5,
                     kernel='rbf', max_iter=-1, probability=False,
                     random_state=None, shrinking=True, tol=0.001,
                     verbose=False))],
         verbose=False)

In [32]:
rbf_kernel_svm_clf.predict([[0.620850,0.547122]])

array([0])

# **SVM** **REGRESSION**

## **1.** **Linear** **SVM** **Regression**

In [31]:
svm_reg=LinearSVR(epsilon=1.5)
svm_reg.fit(X,y)

/usr/local/lib/python3.7/dist-packages/sklearn/utils/validation.py:760: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


LinearSVR(C=1.0, dual=True, epsilon=1.5, fit_intercept=True,
          intercept_scaling=1.0, loss='epsilon_insensitive', max_iter=1000,
          random_state=None, tol=0.0001, verbose=0)

In [36]:
svm_reg.predict([[0.620850,0.547122]])

array([0.])

## **1.** **Non-** **Linear** **SVM** **Regression**  **(Kernalized)**

In [34]:
poly_kernel_svm_reg=Pipeline([
                              ('std_scaler',StandardScaler()),
                              ('poly_svr',SVR(kernel='poly',degree=2,C=100,epsilon=0.1))
])
poly_kernel_svm_reg.fit(X,y)

/usr/local/lib/python3.7/dist-packages/sklearn/utils/validation.py:760: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


Pipeline(memory=None,
         steps=[('std_scaler',
                 StandardScaler(copy=True, with_mean=True, with_std=True)),
                ('poly_svr',
                 SVR(C=100, cache_size=200, coef0=0.0, degree=2, epsilon=0.1,
                     gamma='scale', kernel='poly', max_iter=-1, shrinking=True,
                     tol=0.001, verbose=False))],
         verbose=False)

In [37]:
poly_kernel_svm_reg.predict([[0.620850,0.547122]])


array([0.90815076])